package com.wjh.ims.dal.mapper.priceTemplate;

import com.wjh.ims.dal.model.priceTemplate.GoodsPriceTemplate;
import com.wjh.ims.dal.model.priceTemplate.GoodsPriceTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsPriceTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    int countByExample(GoodsPriceTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    int deleteByExample(GoodsPriceTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    int insert(GoodsPriceTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    int insertSelective(GoodsPriceTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    List<GoodsPriceTemplate> selectByExample(GoodsPriceTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    GoodsPriceTemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") GoodsPriceTemplate record, @Param("example") GoodsPriceTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    int updateByExample(@Param("record") GoodsPriceTemplate record, @Param("example") GoodsPriceTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsPriceTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_template
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    int updateByPrimaryKey(GoodsPriceTemplate record);
}