package com.wjh.ims.dal.model.priceTemplate;

public class GoodsPriceTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_template.id
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_template.goods_id
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_template.template_id
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_template.price
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_template.discount
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    private Integer discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_price_template.id
     *
     * @return the value of goods_price_template.id
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_price_template.id
     *
     * @param id the value for goods_price_template.id
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_price_template.goods_id
     *
     * @return the value of goods_price_template.goods_id
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_price_template.goods_id
     *
     * @param goodsId the value for goods_price_template.goods_id
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_price_template.template_id
     *
     * @return the value of goods_price_template.template_id
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_price_template.template_id
     *
     * @param templateId the value for goods_price_template.template_id
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_price_template.price
     *
     * @return the value of goods_price_template.price
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_price_template.price
     *
     * @param price the value for goods_price_template.price
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_price_template.discount
     *
     * @return the value of goods_price_template.discount
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_price_template.discount
     *
     * @param discount the value for goods_price_template.discount
     *
     * @mbggenerated Mon Mar 25 13:50:12 CST 2019
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
}