package com.wjh.ims.dal.model.priceTemplate;

import java.util.Date;

public class PriceTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_template.id
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_template.no
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_template.name
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_template.type
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_template.remarks
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_template.gmt_create
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_template.gmt_modified
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_template.id
     *
     * @return the value of price_template.id
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_template.id
     *
     * @param id the value for price_template.id
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_template.no
     *
     * @return the value of price_template.no
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_template.no
     *
     * @param no the value for price_template.no
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_template.name
     *
     * @return the value of price_template.name
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_template.name
     *
     * @param name the value for price_template.name
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_template.type
     *
     * @return the value of price_template.type
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_template.type
     *
     * @param type the value for price_template.type
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_template.remarks
     *
     * @return the value of price_template.remarks
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_template.remarks
     *
     * @param remarks the value for price_template.remarks
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_template.gmt_create
     *
     * @return the value of price_template.gmt_create
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_template.gmt_create
     *
     * @param gmtCreate the value for price_template.gmt_create
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_template.gmt_modified
     *
     * @return the value of price_template.gmt_modified
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_template.gmt_modified
     *
     * @param gmtModified the value for price_template.gmt_modified
     *
     * @mbggenerated Mon Mar 25 13:56:23 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}