package com.wjh.ims.dal.model.customer;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.id
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.name
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.no
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.abbr
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String abbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.address
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.contacts
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.contacts_phone
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String contactsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.type
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.tax_num
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String taxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.remarks
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.bank
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.bank_no
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.gmt_create
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.gmt_modified
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.id
     *
     * @return the value of customers.id
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.id
     *
     * @param id the value for customers.id
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.name
     *
     * @return the value of customers.name
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.name
     *
     * @param name the value for customers.name
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.no
     *
     * @return the value of customers.no
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.no
     *
     * @param no the value for customers.no
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.abbr
     *
     * @return the value of customers.abbr
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getAbbr() {
        return abbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.abbr
     *
     * @param abbr the value for customers.abbr
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setAbbr(String abbr) {
        this.abbr = abbr == null ? null : abbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.address
     *
     * @return the value of customers.address
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.address
     *
     * @param address the value for customers.address
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.contacts
     *
     * @return the value of customers.contacts
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.contacts
     *
     * @param contacts the value for customers.contacts
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.contacts_phone
     *
     * @return the value of customers.contacts_phone
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getContactsPhone() {
        return contactsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.contacts_phone
     *
     * @param contactsPhone the value for customers.contacts_phone
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setContactsPhone(String contactsPhone) {
        this.contactsPhone = contactsPhone == null ? null : contactsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.type
     *
     * @return the value of customers.type
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.type
     *
     * @param type the value for customers.type
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.tax_num
     *
     * @return the value of customers.tax_num
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getTaxNum() {
        return taxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.tax_num
     *
     * @param taxNum the value for customers.tax_num
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setTaxNum(String taxNum) {
        this.taxNum = taxNum == null ? null : taxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.remarks
     *
     * @return the value of customers.remarks
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.remarks
     *
     * @param remarks the value for customers.remarks
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.bank
     *
     * @return the value of customers.bank
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.bank
     *
     * @param bank the value for customers.bank
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.bank_no
     *
     * @return the value of customers.bank_no
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.bank_no
     *
     * @param bankNo the value for customers.bank_no
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.gmt_create
     *
     * @return the value of customers.gmt_create
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.gmt_create
     *
     * @param gmtCreate the value for customers.gmt_create
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.gmt_modified
     *
     * @return the value of customers.gmt_modified
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.gmt_modified
     *
     * @param gmtModified the value for customers.gmt_modified
     *
     * @mbggenerated Mon Mar 25 10:15:58 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}