package com.wjh.ims.dal.model.goods;

import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_no
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private String goodsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type_no
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private String typeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.spell
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private String spell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.spec
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.aux_unit_first
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private String auxUnitFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.aux_unit_second
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private String auxUnitSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.aux_val_first
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private Integer auxValFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.aux_val_second
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private Integer auxValSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.num
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.effective_days
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private Integer effectiveDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remarks
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_create
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_modified
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_no
     *
     * @return the value of goods.goods_no
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public String getGoodsNo() {
        return goodsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_no
     *
     * @param goodsNo the value for goods.goods_no
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setGoodsNo(String goodsNo) {
        this.goodsNo = goodsNo == null ? null : goodsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type_no
     *
     * @return the value of goods.type_no
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public String getTypeNo() {
        return typeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type_no
     *
     * @param typeNo the value for goods.type_no
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setTypeNo(String typeNo) {
        this.typeNo = typeNo == null ? null : typeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.spell
     *
     * @return the value of goods.spell
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public String getSpell() {
        return spell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.spell
     *
     * @param spell the value for goods.spell
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setSpell(String spell) {
        this.spell = spell == null ? null : spell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.spec
     *
     * @return the value of goods.spec
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.spec
     *
     * @param spec the value for goods.spec
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.aux_unit_first
     *
     * @return the value of goods.aux_unit_first
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public String getAuxUnitFirst() {
        return auxUnitFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.aux_unit_first
     *
     * @param auxUnitFirst the value for goods.aux_unit_first
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setAuxUnitFirst(String auxUnitFirst) {
        this.auxUnitFirst = auxUnitFirst == null ? null : auxUnitFirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.aux_unit_second
     *
     * @return the value of goods.aux_unit_second
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public String getAuxUnitSecond() {
        return auxUnitSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.aux_unit_second
     *
     * @param auxUnitSecond the value for goods.aux_unit_second
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setAuxUnitSecond(String auxUnitSecond) {
        this.auxUnitSecond = auxUnitSecond == null ? null : auxUnitSecond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.aux_val_first
     *
     * @return the value of goods.aux_val_first
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public Integer getAuxValFirst() {
        return auxValFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.aux_val_first
     *
     * @param auxValFirst the value for goods.aux_val_first
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setAuxValFirst(Integer auxValFirst) {
        this.auxValFirst = auxValFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.aux_val_second
     *
     * @return the value of goods.aux_val_second
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public Integer getAuxValSecond() {
        return auxValSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.aux_val_second
     *
     * @param auxValSecond the value for goods.aux_val_second
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setAuxValSecond(Integer auxValSecond) {
        this.auxValSecond = auxValSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.num
     *
     * @return the value of goods.num
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.num
     *
     * @param num the value for goods.num
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.effective_days
     *
     * @return the value of goods.effective_days
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public Integer getEffectiveDays() {
        return effectiveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.effective_days
     *
     * @param effectiveDays the value for goods.effective_days
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setEffectiveDays(Integer effectiveDays) {
        this.effectiveDays = effectiveDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remarks
     *
     * @return the value of goods.remarks
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remarks
     *
     * @param remarks the value for goods.remarks
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gmt_create
     *
     * @return the value of goods.gmt_create
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gmt_create
     *
     * @param gmtCreate the value for goods.gmt_create
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gmt_modified
     *
     * @return the value of goods.gmt_modified
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gmt_modified
     *
     * @param gmtModified the value for goods.gmt_modified
     *
     * @mbggenerated Sun Mar 24 17:59:24 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}