package com.wjh.ims.dal.model.menu;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.node_id
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    private String nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.qtitle
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    private String qtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.leaf
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    private Boolean leaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.level
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_id
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    private String parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.node_id
     *
     * @return the value of menu.node_id
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.node_id
     *
     * @param nodeId the value for menu.node_id
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.qtitle
     *
     * @return the value of menu.qtitle
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public String getQtitle() {
        return qtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.qtitle
     *
     * @param qtitle the value for menu.qtitle
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public void setQtitle(String qtitle) {
        this.qtitle = qtitle == null ? null : qtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.leaf
     *
     * @return the value of menu.leaf
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public Boolean getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.leaf
     *
     * @param leaf the value for menu.leaf
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public void setLeaf(Boolean leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.level
     *
     * @return the value of menu.level
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.level
     *
     * @param level the value for menu.level
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent_id
     *
     * @return the value of menu.parent_id
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent_id
     *
     * @param parentId the value for menu.parent_id
     *
     * @mbggenerated Sun Sep 16 13:11:43 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }
}