package com.wjh.ims.dal.model.supplier;

import java.util.Date;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.id
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.name
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.no
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.abbr
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String abbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.address
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contacts
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contacts_phone
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String contactsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.bank
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.bank_no
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.remarks
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.gmt_create
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.gmt_modified
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.id
     *
     * @return the value of supplier.id
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.id
     *
     * @param id the value for supplier.id
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.name
     *
     * @return the value of supplier.name
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.name
     *
     * @param name the value for supplier.name
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.no
     *
     * @return the value of supplier.no
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.no
     *
     * @param no the value for supplier.no
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.abbr
     *
     * @return the value of supplier.abbr
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getAbbr() {
        return abbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.abbr
     *
     * @param abbr the value for supplier.abbr
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setAbbr(String abbr) {
        this.abbr = abbr == null ? null : abbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address
     *
     * @return the value of supplier.address
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address
     *
     * @param address the value for supplier.address
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contacts
     *
     * @return the value of supplier.contacts
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contacts
     *
     * @param contacts the value for supplier.contacts
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contacts_phone
     *
     * @return the value of supplier.contacts_phone
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getContactsPhone() {
        return contactsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contacts_phone
     *
     * @param contactsPhone the value for supplier.contacts_phone
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setContactsPhone(String contactsPhone) {
        this.contactsPhone = contactsPhone == null ? null : contactsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.bank
     *
     * @return the value of supplier.bank
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.bank
     *
     * @param bank the value for supplier.bank
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.bank_no
     *
     * @return the value of supplier.bank_no
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.bank_no
     *
     * @param bankNo the value for supplier.bank_no
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.remarks
     *
     * @return the value of supplier.remarks
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.remarks
     *
     * @param remarks the value for supplier.remarks
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.gmt_create
     *
     * @return the value of supplier.gmt_create
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.gmt_create
     *
     * @param gmtCreate the value for supplier.gmt_create
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.gmt_modified
     *
     * @return the value of supplier.gmt_modified
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.gmt_modified
     *
     * @param gmtModified the value for supplier.gmt_modified
     *
     * @mbggenerated Mon Mar 25 10:01:37 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}